### ISSUE TITLE
Better Symfony 7 support

### ISSUE THREAD

**Issue by sukhwinder33445** [overtrue/phplint#196]
# New Issue

`PHP Fatal error:  Declaration of Overtrue\PHPLint\Console\Application::doRun(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Application::doRun(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /home/runner/work/My_Module/vendor/overtrue/phplint/src/Console/Application.php on line 50`

## Diagnose
Installed with : Run composer require -n --no-progress overtrue/phplint
Version: (9.0.5)
PhpVersion: > 8.1

**Comment by llaville** [comment]
Related to PR #195. Allowing Symfony 7 components depencencies by Composer constraint was not enough to add full support to SF 7.
Especially because SF components signature has changed by adding return type hint.

This is the reason while it does not works on PHP 8.2 and 8.3 that install Symfony v7.0 component, 
and while it works fine on PHP 8.1 that still install Symfony v6.4 components (signature compatible).

**Comment by llaville** [comment]
v9.0.6 is now available
